-- Temporarily disable RLS for testing
ALTER TABLE monthly_reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE video_analytics DISABLE ROW LEVEL SECURITY;
ALTER TABLE channels DISABLE ROW LEVEL SECURITY;
